name: Deploy App A

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
      environment:
        type: choice
        description: Deploymnent target
        required: true
        options: 
        - app_b-dev
        - app_b-prod
env:
  TAG: ${{ github.event.inputs.tag }}
  GH_TOKEN: ${{ github.token }}
  APP_PATH: app_b
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Secret
        run: echo ${{ secrets.A_SECRET }}

      - name: Variable
        run: echo ${{ vars.A_VARIABLE }}
        
      - name: Init Git
        run: |
          git init
          git remote add origin ${{github.server_url}}/${{github.repository}}
      - name: Get artifact
        run: |
          gh release download $TAG --pattern $TAG.tar.gz
          tar -xzvf $TAG.tar.gz
          cat $APP_PATH/readme.md
