name: Build

on:
  push:
    branches: ['main']
    paths: ['app_a/**']
  workflow_dispatch:

env:
  app_name: app_a
  app_path: app_a

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: "${{ env.app_name }}-${{ github.run_number }}-${{ github.run_attempt }}"
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Tag
        run: | 
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action"
          git tag -a ${{env.TAG}} $GITHUB_SHA -m ""
          git push origin ${{env.TAG}}
          
      - name: Package
        run: |           
          echo ${{env.TAG}} >> ${{env.app_path}}/readme.md
          tar -czvf ${{env.TAG}}.tar.gz ${{env.app_path}}
          
      - name: Release
        run: |
          gh release create ${{env.TAG}} ${{env.TAG}}.tar.gz \
            --generate-notes \
            --draft