name: Build
on:
  push:
    branches: ['main']
    paths: ['app_a/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: "app-a-${{ github.run_number }}-${{ github.run_attempt }}"
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Tag
        run: | 
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action"
          git tag -a ${{env.TAG}} $GITHUB_SHA -m ""
          git push origin ${{env.TAG}}
          
      - name: Package
        run: |           
          echo ${{env.TAG}} >> app-a/readme.md
          tar -czvf app-a.tar.gz app-a
          
      - name: Release
        run: |
          gh release create ${{env.TAG}} app-a.tar.gz \
            --title "App A ${{ github.run_number }}-${{ github.run_attempt }}"  \
            --generate-notes \
            --draft
