name: Build App A

on:
  workflow_dispatch:
    inputs:
      target:
        required: false
  push:
    branches: ['main']
    paths: ['app_a/**']
  
env:
  APP_NAME: app_a
  APP_PATH: app_a
  TAG: "app_a-${{ github.run_number }}.${{ github.run_attempt }}"
  GH_TOKEN: ${{ github.token }}
  TARGET: ${{ github.event.inputs.target || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: ${{env.TARGET}}
          fetch-tags: true

      - name: Package
        run: tar -czvf $TAG.tar.gz $APP_PATH

      # https://cli.github.com/manual/gh_release_list
      # https://cli.github.com/manual/gh_release_delete
      - name: Clean Previous Drafts
        run: |
          gh release list \
            --json isDraft,tagName \
            --jq '.[] | select(.isDraft and (.tagName | startswith($ENV.APP_NAME))) | .tagName' \
          | xargs -I {} gh release delete {} -y --cleanup-tag

      # https://cli.github.com/manual/gh_release_create
      - name: Release
        run: |
          echo Creating github release from $TARGET
          gh release create $TAG $TAG.tar.gz \
            --target $TARGET \
            --generate-notes \
            --draft
