name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        
env:
  TAG: ${{ github.event.inputs.tag }}
  GH_TOKEN: ${{ github.token }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Init Git
        run: |
          git init
          git remote add origin ${{github.server_url}}/${{github.repository}}
      - name: Get artifact
        run: |
          echo Time to release ${{env.TAG}}
          gh release download ${{env.TAG}} --pattern app-a.tar.gz
          tar -xzvf app-a.tar.gz
          cat app-a/readme.md
