name: Deploy
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${GITHUB_REF#refs/*/}
    steps:
      - name: Get artifact
        run: |
          echo Time to release ${{env.TAG}}
          gh release download ${{env.TAG}} --pattern app-a.tar.gz
          tar -xzvf app-a.tar.gz
          ls
