name: Deploy
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.release_tag || github.ref_name }}
    steps:
      - name: Get artifact
        run: |
          echo Time to release ${{env.TAG}}
          gh release download ${{env.TAG}} --pattern app-a.tar.gz
          tar -xzvf app-a.tar.gz
          cat app-a/readme.md
