name: Release Router

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        required: true
            
env:
  GH_TOKEN: ${{ github.token }}
  TAG: ${{github.event.inputs.tag || github.ref_name}}
    
jobs:
  select-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Init Git
        run: |
          git init
          git remote add origin ${{github.server_url}}/${{github.repository}}

      - name: Release App A
        if: ${{ startsWith(env.TAG, 'app_a') }}
        run: |
          echo "Deploying App A"
          gh workflow run app_a-deploy.yml \ 
            --ref $TAG \
            --field tag=$TAG \
            --field environment=app_a-prod

      - name: Release App B
        if: ${{ startsWith(env.TAG, 'app_b' )}}
        run: |
          echo "Deploying App B"
          gh workflow run app_b-deploy.yml
            --ref $TAG \
            --field tag=$TAG \
            --field environment=app_b-prod
